reanahub/reana-workflow-engine-yadage

Dockerfile
reana_workflow_engine_yadage/celeryapp.py
reana_workflow_engine_yadage/tasks.py

* Previous module structure imports have been renamed to
to current reana_workflow_engine_yadage and therefore Dockerfile
has been amended. (closes #10)

celery: fix module imports

---

CONTRIBUTING.rst
README.rst
docs/conf.py
docs/contributing.rst
docs/gettingstarted.rst
docs/index.rst
docs/introduction.rst
docs/requirements.txt
docs/usage.rst

* Adds more documentation chapters (Introduction, Getting started,
Contributing).
* Adds Travis/Coveralls/RFTD/Waffle/Travis/License badges.
* Adds `docs/requirements.txt` so that ReadTheDocs can install all the
prerequisites for building the autodoc parts of the documentation.

docs: structure improvements and new chapters

---

reana_workflow_engine_yadage/submit.py

* Updates API call for reana-job-controller because API versioning
was removed from URLs. See reanahub/reana-job-controller#15.
(closes #22)

job-submission: fix reana-job-controller API call

---

reana_workflow_engine_yadage/submit.py

* Adds call to the job's log endpoint. Not connected to `yadage` yet.
* Fixes job controller API fields names according to last version.

job-submission: add job logs call

---

Dockerfile
reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tasks.py
reana_workflow_engine_yadage/zeromq_tracker.py
setup.py

* Since `yadage` 0.12.13 workflow file submission is supported so
no need to have `yadage-fork` anymore.

installation: update to last `yadage` version

---

reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/tasks.py

config: set canonical location to read inputs

---

reana_workflow_engine_yadage/tasks.py

inputs: fix typo in steering_ctx kwargs

---

setup.py

* Declares support for Python-2.7 used in Fedora-25 based container.

installation: Python-2.7

---

reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/tasks.py

* Since `yadage` doesn't support yet providing more than one init dir
a code/input will be copied to a single parent dir and provided
to `yadage` as input.
* Fixes outputs retrieval. (whole workflow dir copied inside a
canonical directory for outputs).

tasks: copy inputs/code/outputs to canonical dirs

---

Dockerfile
reana_workflow_engine_yadage/celeryapp.py
reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tasks.py
requirements-dev.txt
setup.py

* Publishes workflow status to message broker instead of accessing the DB.
(Should be merged after https://github.com/reanahub/reana-workflow-engine-yadage/pull/63)

global: declare queues in message broker

---

reana_workflow_engine_yadage/version.py
setup.py

* Introduces more upper boundary limits for selected important
dependencies (Bravado, Celery) for the cluster components.
(addresses reanahub/reana#80)

installation: more version limits

---

reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tasks.py
setup.py

* Adds click to enable one time run of yadage engines. Before celery was
running as a service waiting for requests, now by having a command we
enable REANA to spawn workflows on demand. Closes #94

global: workflow engine independent of celery

---

reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tasks.py
reana_workflow_engine_yadage/tracker.py
reana_workflow_engine_yadage/utils.py
setup.py

* Centralises the initialisation of WorkflowStatusPublisher
using a Singleton to facilitate debugging and error reporting.
* This work needs to be completed but paves the way for improving
error reporting for workflow engines on publishing errors
(connects reanahub/reana-workflow-controller#172).

publisher: improve error reporting

---

setup.py

* Removes r-w-monitor and zeromq cluster components that were not used since
many moons. Helps to make the cluster slimmer and faster.
(connects reanahub/reana-cluster#169)

global: removal of r-w-monitor and zeromq

---

reana_workflow_engine_yadage/externalbackend.py
setup.py

* To enable cache R-J-C needs workflow uuid for getting
workspace path.
Connects reanahub/reana-job-controller/issues/118

externalbackend: pass workflow uuid for R-J-C

---

reana_workflow_engine_yadage/tasks.py
setup.py

* When job controller and workflow engines run in the same pod,
workflow engine has to ensure that job controller is ready to
receive requests.
Connects reanahub/reana-job-controller/issues/105

tasks: adds connectivity to job controller check

---

.travis.yml
AUTHORS.rst
Dockerfile
reana_workflow_engine_yadage/cli.py
reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tracker.py
reana_workflow_engine_yadage/version.py
setup.py

* Closes #114
* Closes #124
Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>

externalbackend: upgraded yadage

---

reana_workflow_engine_yadage/externalbackend.py

This PR reverts back CMD encoding which was deleted in https://github.com/reanahub/reana-workflow-engine-yadage/commit/e4d0cb496a9005ef1fab12ec21b922d4db415210

externalbackend: reverts back cmd encoding

---

reana_workflow_engine_yadage/cli.py

* If there is no workflow specification provided to the workflow
engine, a new parameter can be passed. This is the relative
path to the workflow file. This is needed for the case of running
a workflow triggered by a Git provider, i.e. on commit to master,
so we expect the analysis code to be present in the workflow
workspace and, hence, we can load it (closes reanahub/reana#235).

cli: accept workflow file location

---

reana_workflow_engine_yadage/externalbackend.py

* Fixes support for specifying wanted image tag in Yadage workflow
definition files. (closes #143)
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

yadage: fix image tag support

---

AUTHORS.rst
CHANGES.rst
reana_workflow_engine_yadage/cli.py
setup.py

Add operational option `initfiles` that people can use in their reana.yaml, similarly to the options initdir and toplevel. `initfiles` expects an array of files to read the input parameters from.
Example
```
inputs:
options:
initfiles: 
- workflow/yadage/input_filenames.yml
- workflow/yadage/input_cross_sections.yml
```
closes reanahub/reana#305

Operational options: add initfiles

---

.travis.yml
CHANGES.rst
Dockerfile
requirements.txt
setup.py

Closes reanahub/reana#352
Package `enum34` is not compatible with Python 3.6 and later versions. Is not needed in the code so I removed it from `setup.py`.

migrate to python 3.8

---

reana_workflow_engine_yadage/version.py
requirements.txt
setup.py

closes reanahub/reana-demo-bsm-search#21
[`jq` was hard-pinned](https://github.com/reanahub/reana-workflow-engine-yadage/commit/5307900773116a69e48a19d921d2b39437eb1baf#diff-2eeaed663bd0d25b7e608891384b7298L47) in the past, perhaps for a reason.
Steps:
```console
$ cd ../reana-workflow-engine-yadage
$ gh pr checkout 161
$ reana-dev docker-build -b DEBUG=1 -c reana-workflow-engine-yadage --no-cache
$ reana-dev kind-load-docker-image -c reana-workflow-engine-yadage
$ reana-dev python-install-eggs
$ reana-dev cluster-undeploy
$ reana-dev cluster-deploy --mode debug --admin-email jdoe@example.org --admin-password 123456 --exclude-components r-ui
$ eval $(reana-dev client-setup-environment)
$ reana-client ping
$ cd ../reana-demo-bsm-search
$ reana-client run -w bsm
...
$ reana-client status -w …
```

setup: fix bsm example slowness

---

CHANGES.rst
reana_workflow_engine_yadage/cli.py

Add `accept_metadir` to allow overwriting the yadage meta directory `_yadage` that exist if you restart a workflow in yadage workspace.
closes reanahub/reana-server#293

Add accept_metadir

---

reana_workflow_engine_yadage/cli.py
reana_workflow_engine_yadage/utils.py
requirements.txt
setup.py

* Uses REANA-Commons decorator to handle termination signals in the
workflow engine container by notifying the system about the failure
and registering the workflow as failed.
Addresses reanahub/reana#478

global: handle termination signals

---

CHANGES.rst
reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tracker.py

* Renames ``succeeded`` to ``finished`` as the latter is the one
described centrally in ``reana_db.models.WorkflowStatus`` and
``reana_db.models.JobStatus``.

global: rename job status succeeded

---

CHANGES.rst
reana_workflow_engine_yadage/externalbackend.py
requirements.txt
setup.py

* Let `JobControllerAPIClient` take care of serialisation internally
(through `reana_commons.job_utils.serialise_job_command`).
Closes reanahub/reana-job-controller#304.

global: harmonise job command treatment

---

README.rst
requirements.txt
setup.py

This PR removes `sqlalchemy` and `sqlalchemy-utils` from the list of project requirements. The list of `requirements.txt` has been updated accordingly.
When running the project Python tests:
```
./run-tests.sh --check-pytest
```
They fail because of a version of _SQLAlchemy_ that _SQLAlchemy-utils_ do not support yet (version `1.4.0`+). They currently have an [open issue](https://github.com/kvesteri/sqlalchemy-utils/issues/505) about this, and I believe Diego [has already fix this in other REANA repos](https://github.com/reanahub/reana-db/commit/221ee727802988bc11b329a3dba96f47d701fdc2) (i.e. `reana-db`).
Same case as `reana-db`, this repository also contains _SQLAlchemy_ and _SQLAlchemy-utils_ as dependencies. So, in principle, the same patch would be required.
However, taking a look at …

installation: remove legacy sqlalchemy

---

reana_workflow_engine_yadage/externalbackend.py

* This message wasn't correctly formatted, therefore, RWC wasn't
marking the job as started in the DB.
To test:
- You should run a Yadage workflow and see that the `Started` and `Finished` attributes are filled in `reana-client logs -w workflow-name`.
**Why was this happening?**
The [job status consumer in RWC](https://github.com/reanahub/reana-workflow-controller/blob/ae4f10e1daa942b4e02f65f58a7c879f3fb9529e/reana_workflow_controller/consumer.py#L50) wouldn't understand the malformed dictionary, because the keys do not comply with [what it expects](https://github.com/reanahub/reana-workflow-controller/blob/ae4f10e1daa942b4e02f65f58a7c879f3fb9529e/reana_workflow_controller/consumer.py#L175).
Errors like this are very dangerous and very difficult to spot. Perhaps a solution would be to …

publisher: fix progress update message

---

AUTHORS.rst
reana_workflow_engine_yadage/cli.py
requirements.txt
setup.py

Delete the dependency on SHARED_VOLUME_PATH by storing the full path inside the database, for serial, yadage and cwl engines.
Closes reanahub/reana-db#94

cli: modify  workspace_path to store full path

---

Dockerfile

Fixes problem with `python-pip` package.
```console
docker build --no-cache -t reanahub/reana-workflow-engine-yadage:latest .
[+] Building 3.2s (6/13)                                                                                                                                                                                                                                                                                                    
=> [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                   0.0s
=> => transferring dockerfile: 1.44kB …
```

docker: pin base image

---

CHANGES.rst
reana_workflow_engine_yadage/cli.py
reana_workflow_engine_yadage/tracker.py

- removes case when Yadage engine fails before running status is published leaving workflow in pending state.
- one additional MQ message is sent at the beginning of each Yadage workflow.
closes #216
How to test:
You can pretty much the scenario described in the issue. Details:
1. Go to `helloworld` workflow demo. Edit parameters in `reana-yadage.yaml` to be incorrect. For example, changing `sleeptime` to `sleept`;
2. Run the workflows, `reana-client run -w yadage -f reana-yadage.yaml`;
3. Workflow should fail.

tracker: publish running status before Yadage init

---

CHANGES.rst
reana_workflow_engine_yadage/externalbackend.py
tests/test_externalbackend.py

closes reanahub/reana-job-controller#343
How to test:
This PR is part of a bigger group of PRs. Please refer to the addressed issue to see all of them.
1. Modify Yadage helloworld example, with `kubernetes_job_timeout=20` (in seconds) and `sleeptime=2` (2 seconds so the workflow will definitely run longer than 20 seconds):
`reana-yadage.yml`
```yaml
...
parameters:
sleeptime: 2  # <= here
inputfile: data/names.txt
helloworld: code/helloworld.py
...
```
`workflow/yadage/workflow.yaml`
```yaml
...
environment:
environment_type: 'docker-encapsulated'
image: 'python'
imagetag: '2.7-slim'
resources:
- kubernetes_job_timeout: 20  # <= here
...
```
2. Start workflow `reana-client run -w yadage-timeout -f reana-yadage.yaml`
3. After 25-30 seconds, check using `reana-client list` if workflow …

add kubernetes_job_timeout parameter

---

CHANGES.rst
docs/conf.py
reana_workflow_engine_yadage/version.py
requirements.in
requirements.txt
setup.py

release: 0.8.1

---

CHANGES.rst
reana_workflow_engine_yadage/version.py
requirements.txt
setup.py

addresses https://github.com/reanahub/reana-workflow-engine-yadage/issues/222

Release 0.8.2

---

Dockerfile

When building the image with latest `python:3.8-slim-buster`, the build
times were unusually slow because some of the dependencies wanted to
bring over Python 2 instead of Python 3 libraries. This commit fixes the
problem and makes the build process fast again.
(However, Python 3.7 system packages are still being brought, which is
inconsistent with Python 3.8 version that the image provides. An upgrade
to Python 3.9 or a replacement of the base image may be wanted soon.)

docker: adapt to latest python:3.8-slim-buster

---

CHANGES.rst
reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/externalbackend.py
requirements.txt
setup.py
tests/test_externalbackend.py

closes #231 
How to test:
```diff
diff --git a/reana-yadage.yaml b/reana-yadage.yaml
index d00859b..41f1834 100644
--- a/reana-yadage.yaml
+++ b/reana-yadage.yaml
@@ -11,6 +11,8 @@ inputs:
helloworld: code/helloworld.py
workflow:
type: yadage
+  resources:
+    kerberos: true
file: workflow/yadage/workflow.yaml
outputs:
files:
```
```diff
diff --git a/workflow/yadage/workflow.yaml b/workflow/yadage/workflow.yaml
index 16bc4a5..0222902 100644
--- a/workflow/yadage/workflow.yaml
+++ b/workflow/yadage/workflow.yaml
@@ -25,12 +25,12 @@ stages:
step:
process:
process_type: 'string-interpolated-cmd'
-          cmd: 'python "{helloworld}" --sleeptime {sleeptime} --inputfile "{inputfile}" --outputfile "{
outputfile}"'
+          cmd: 'klist 2>&1; exit 0'
publisher:
publisher_type: 'frompar-pub' …
```

add global Kerberos propagation 

---

CHANGES.rst
requirements.in
requirements.txt
setup.py

Upgrades `jq` Python dependency, fixing the container image building process on the arm64 architecture.
Closes reanahub/reana#753.

installation: upgrade jq dependency

---

CHANGES.rst
Dockerfile
reana_workflow_engine_yadage/version.py
requirements.in
requirements.txt
setup.py

Changes `jq` dependency version on amd64 architecture to older version, making certain Yadage workflows much faster.
Closes reanahub/reana-demo-bsm-search#21

installation: faster jq on amd64

---

AUTHORS.rst
reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/externalbackend.py

Closes reanahub/reana-workflow-controller#546

fix(progress): correctly handle running and stopped jobs (#258)

---

AUTHORS.md
reana_workflow_engine_yadage/externalbackend.py

This pull request add support for user configurable parameters in the Compute4PUNCH backend. See https://github.com/reanahub/reana-job-controller/pull/430.

feat(api) Add support for the Compute4PUNCH backend

---

.github/workflows/ci.yml
setup.py

BREAKING CHANGE: drop support for Python 3.6 and 3.7
Closes reanahub/reana#784

build(python): drop support for Python 3.6 and 3.7 (#267)

---

reana_workflow_engine_yadage/tracker.py
tests/test_tracker.py

The `planned` status is not defined or used anywhere in REANA and it was
simply ignored.
Closes #255

fix(tracker): remove invalid `planned` state (#268)

---

.github/workflows/ci.yml
requirements.in
requirements.txt
setup.py

Adds forgotten pin to `requirements.txt` on the `jq` version for aarch64/arm64 architectures.
Downgrades `jq` version to 1.2.2 to be closer to the one used for amd64 architectures.
This solves the problem of running Yadage workflows on aarch64/arm64 platforms.
Closes #281

build(python): use jq 1.2.2 on aarch64/arm64

---

.editorconfig
.github/workflows/ci.yml
.markdownlint.yaml
.prettierignore
.prettierrc.yaml
.release-please-config.json
.yamllint.yaml
AUTHORS.md
CHANGELOG.md
CONTRIBUTING.md
MANIFEST.in
README.md
docs/index.md
run-tests.sh

Introduce remaining file formatting checks to `run-tests.sh` and to the GitHub CI:
Closes #287

ci(linting): add remaining linting and formatting checks
