Dockerfile

docker: fix CentOS Rpmdb checksum problem

---

Dockerfile

Signe:-off-by: lukasheinrich <lukas.heinrich@gmail.com>

docker: try fixing docker build on CI

---

reana_workflow_engine_yadage/tasks.py

persistence: update directory structure

---

setup.py

setup: fix yadage dependency pinning

---

reana_workflow_engine_yadage/tasks.py

persistence: amend default user name

---

reana_workflow_engine_yadage/externalbackend.py

job-submission: fix hardcoded organization string

---

setup.py

installation: use yadage-fork

---

reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/database.py
reana_workflow_engine_yadage/models.py
reana_workflow_engine_yadage/tasks.py
setup.py

* (closes reanahub/reana-workflow-controller#28).

db: move fsdb to sqlite

---

reana_workflow_engine_yadage/models.py
reana_workflow_engine_yadage/tasks.py

tasks: receive workflow uuid and workspace

---

reana_workflow_engine_yadage/tasks.py

outputs: symlink workflow dir to `outputs` dir

---

AUTHORS.rst
README.rst
docs/authors.rst
docs/changes.rst
docs/conf.py
docs/contributing.rst
docs/gettingstarted.rst
docs/index.rst
docs/introduction.rst
docs/license.rst

* Enhances documentation structure, updates author list, updates short
description and feature list.

docs: better structure

---

AUTHORS.rst

docs: standardised list itemisation

---

CHANGES.rst
reana_workflow_engine_yadage/version.py

release: v0.1.0

---

reana_workflow_engine_yadage/version.py

version: post-release bump

---

reana_workflow_engine_yadage/models.py

models: update workflow model to contain log field

---

reana_workflow_engine_yadage/celeryapp.py
reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/submit.py

* Moves JOBCONTROLLER_HOST variable to config.py
and makes it configureable through an environment variable.

config: addition of JOBCONTROLLER_HOST

---

AUTHORS.rst
reana_workflow_engine_yadage/version.py

docs: author ORCID links

---

Dockerfile
reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/submit.py
reana_workflow_engine_yadage/tasks.py
requirements-dev.txt

submit: fix JobRequest structure

---

reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tasks.py
reana_workflow_engine_yadage/utils.py

tasks: publish workflow_uuid to MQ

---

reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/submit.py
reana_workflow_engine_yadage/tasks.py
setup.py

tasks: single directory for workflow

---

Dockerfile
docs/requirements.txt
requirements-dev.txt
setup.py

global: remove reana-commons dependency

---

reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/submit.py

Closes reanahub/reana-client#126.

job-submission: step name and a prettified cmd

---

reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/submit.py
reana_workflow_engine_yadage/tracker.py

Connect https://github.com/reanahub/reana-commons/issues/24

tasks: progress status renaming 

---

Dockerfile
reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tasks.py
reana_workflow_engine_yadage/tracker.py
reana_workflow_engine_yadage/utils.py
requirements-dev.txt
setup.py

* Imports publisher from reana-commons to publish the workflow
progress.
Connects https://github.com/reanahub/reana-workflow-commons/issues/4
Closes https://github.com/reanahub/reana-workflow-engine-yadage/issues/75

global: use publisher from reana-commons

---

CHANGES.rst
README.rst
reana_workflow_engine_yadage/version.py

release: v0.3.1

---

reana_workflow_engine_yadage/utils.py
setup.py

Connects reanahub/reana-workflow-controller#131.

publisher: update to kombu producer

---

Dockerfile
reana_workflow_engine_yadage/celeryapp.py
reana_workflow_engine_yadage/tasks.py

Connects reanahub/reana-client#194.

tasks: add stop_workflow from reana_commons

---

reana_workflow_engine_yadage/config.py

config: MOUNT_CVMFS as string

---

reana_workflow_engine_yadage/version.py
setup.py

installation: reana-commons with kubernetes

---

Dockerfile
setup.py

docker: slimmer image

---

Dockerfile

* Makes the Docker image slimmer further by another ~230MB.

docker: even slimmer image

---

reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tasks.py
reana_workflow_engine_yadage/tracker.py

logging: logging format from R-Commons

---

AUTHORS.rst
CHANGES.rst
README.rst
docs/conf.py
reana_workflow_engine_yadage/version.py
setup.py

release: v0.5.0

---

reana_workflow_engine_yadage/externalbackend.py
setup.py

externalbackend: allows to set compute backend & kerberos

---

reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tracker.py

* Use default yadage external proxy
* Closes #125

externalproxy: refactor

---

reana_workflow_engine_yadage/cli.py
reana_workflow_engine_yadage/externalbackend.py

* Addresses reanahub/reana-workflow-controller/issues/269

externalbackend: allows overwriting default job uid

---

setup.py

* Upgrades Yadage to 0.20.1 and Adage to 0.10.1. Useful for
simplification of workflow definitions (stages -> steps, permitting
to remove unwrap true clause).
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

installation: Yadage 0.20.1 upgrade

---

Dockerfile
reana_workflow_engine_yadage/cli.py

global: creates workflow visualisation graph by default

---

reana_workflow_engine_yadage/externalbackend.py

* Addresses reanahub/reana-job-controller/issues/238

externalbackend: allows to use unpacked images

---

reana_workflow_engine_yadage/cli.py
reana_workflow_engine_yadage/config.py

Closes reanahub/docs.reana.io#18.

config: use SHARED_VOLUME_PATH from R-Commons

---

reana_workflow_engine_yadage/cli.py

closes reanahub/reana-client#396

yadage: make initdir configurable

---

reana_workflow_engine_yadage/externalbackend.py

kubernetes: add support for voms_proxy

---

CHANGES.rst
README.rst
docs/conf.py
pytest.ini
reana_workflow_engine_yadage/__init__.py
reana_workflow_engine_yadage/cli.py
reana_workflow_engine_yadage/config.py
reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tracker.py
reana_workflow_engine_yadage/utils.py
run-tests.sh
setup.py
tests/test_version.py

global: Black support

---

CHANGES.rst
reana_workflow_engine_yadage/externalbackend.py

Add `htcondor_max_runtime` and `htcondor_accounting_group` to Yadage scheme
Closes reanahub/reana-job-controller#32

Add HTC resources

---

.flake8
.github/workflows/ci.yml
Dockerfile
MANIFEST.in
reana_workflow_engine_yadage/externalbackend.py
reana_workflow_engine_yadage/tracker.py
requirements.txt
run-tests.sh
setup.py

addresses https://github.com/reanahub/reana/issues/450

ci: add hadolint and flake8 linters

---

CHANGES.rst
reana_workflow_engine_yadage/externalbackend.py

closes reanahub/reana-client#496

k8s: allow customising job memory limit for kubernetes backend

---

CHANGES.rst
reana_workflow_engine_yadage/cli.py
requirements.txt
setup.py

closes https://github.com/reanahub/reana-server/issues/358

yadage: load workflow specification from json rather than file

---

reana_workflow_engine_yadage/externalbackend.py

closes https://github.com/reanahub/reana-workflow-engine-yadage/issues/188

yadage: make compatible with yadage string-like resources

---

requirements.txt
setup.py

closes #192
`reana-dev run-example` finished successfully.

setup: install reana-commons with yadage extra

---

reana_workflow_engine_yadage/version.py
requirements.txt
setup.py

release: 0.8.0a2

---

reana_workflow_engine_yadage/externalbackend.py

- reduces amount of info level logs
closes #204

replace some info level logs with debug level

---

CHANGES.rst
reana_workflow_engine_yadage/externalbackend.py

closes https://github.com/reanahub/reana-job-controller/issues/206

slurm: expose some of the job configuration to users

---

AUTHORS.rst
CHANGES.rst
reana_workflow_engine_yadage/externalbackend.py

Closes reanahub/reana-auth-rucio#1.

yadage: add rucio support

---

CHANGES.rst
reana_workflow_engine_yadage/version.py
requirements.txt
setup.py

- installation: bump shared modules
- installation: bump all dependencies
- release: 0.9.1

release: 0.9.1

---

CHANGES.rst
Dockerfile
reana_workflow_engine_yadage/version.py
requirements.txt
setup.py

release: 0.9.2

---

AUTHORS.md
reana_workflow_engine_yadage/externalbackend.py
requirements.txt
setup.py
tests/test_externalbackend.py

feat(externalbackend): pass k8s requests/limits to job-controller
